### ISSUE TITLE
Small typo in figure 2

### ISSUE THREAD

**Issue by fabiogiglietto** [kaslett/Cracking_Open_FB#1]
Hi Kevin,
thanks for sharing the code. While replicating the study for Italy, I noticed a typo in the code that creates figures. In figure 2, Total_shares should be Total_Views.

Best, Fabio

**Comment by kaslett** [comment]
Fabio,

Thank you so much for finding this typo! I really appreciate it. I just revised the code and pushed the new version to the repo. Please let me know if you find anything else. Thanks again!!

Best,

Kevin
